### ISSUE TITLE
Loading packages from file

### ISSUE THREAD

**Issue by ghost** [KingOfL33t/Ikala#2]
Packages can be loaded from a class but the package loading from file is incomplete. This should load a package from file to where the package manager is aware of it, optionally having some configuration for starting on load. No extra features like dependencies or dependency resolution should be added for now as that is a complex task on its own. There will probably be some form of package info associated with or stored in the package jar files which needs to be finalized, but not all features (such as the aforementioned package dependencies) associated with the info need to be working for basic packages to load.

**Comment by Maceris** [comment]
More appropriate for the Ikala Core project
